server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  #  datasource:
  #    url: jdbc:mysql://${DB_HOST:localhost}:3306/bffinder
  #    username: root
  #    password: cpadilla
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true
  #    properties:
  #      hibernate:
  #        format_sql: true
  #    database: mysql
  #    database-platform: org.hibernate.dialect.MySQLDialect
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE #name registered in eureka
          predicates:
            - Path=/user/**
          filters:
            - AuthenticationFilter #name of the filter class, filter for validate token
        #          filters:
        #            - name: CircuitBreaker
        #              args:
        #                name: PRODUCT-SERVICE
        #                fallbackuri: forward:/productServiceFallBack
        #            - name: RequestRateLimiter
        #              args:
        #                redis-rate-limiter.replenishRate: 1
        #                redis-rate-limiter.burstCapacity: 1

        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: PET-SERVICE
          uri: lb://PET-SERVICE
          predicates:
            - Path=/pet/**
          filters:
            - AuthenticationFilter

        - id: SPECIE-SERVICE
          uri: lb://SPECIE-SERVICE
          predicates:
            - Path=/specie/**
          filters:
            - AuthenticationFilter

        - id: BREED-SERVICE
          uri: lb://BREED-SERVICE
          predicates:
            - Path=/breed/**
          filters:
            - AuthenticationFilter

        - id: ADOPTION-POST-SERVICE
          uri: lb://ADOPTION-POST-SERVICE
          predicates:
            - Path=/post/**
          filters:
            - AuthenticationFilter