server:
  port: 8085

spring:
  application:
    name: ADOPTION-POST-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    ## prueba
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 5000
    url: jdbc:mysql://${DB_HOST:localhost}:3306/bffinder
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
