server:
  port: 8080

spring:
  application:
    name: USER-SERVICE
  config:
#    import: 'optional:configserver:'
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/bffinder
    username: root
    password: cpadilla
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect